version: 1
formatters:
  default:
    format: '%(asctime)s:%(name)s:%(module)s:%(funcName)s:%(lineno)d:%(levelname)s:%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  file:
    () : __main__.logpath
    level: DEBUG   
    formatter: default
loggers:
  run_monitor:
    level: DEBUG
    handlers: [console, file]
    propagate: no
