# */15 * * * 4,5,6,7 . /ifs/home/kellys04/.profile; . /ifs/home/kellys04/.bash_profile; /ifs/data/molecpathlab/scripts/automatic-demultiplex.sh >> /ifs/data/molecpathlab/scripts/cron/log/cron.log 2>&1
*/15 * * * 4,5,6,7 . /ifs/data/molecpathlab/scripts/cron/.profile; /ifs/data/molecpathlab/scripts/automatic-demultiplex.sh >> /ifs/data/molecpathlab/scripts/cron/log/cron.log 2>&1
# run every 15 minutes, 0,15,30,45
# run only on Thurs, Fri, Sat, Sun
