analysis_output_dir: /ifs/data/molecpathlab/NGS580_WES
# auto_demultiplex_dir: /ifs/data/molecpathlab/quicksilver/to_be_demultiplexed/NGS580
samplesheet_source_dir: /ifs/data/molecpathlab/quicksilver/to_be_demultiplexed/NGS580
samplesheet_processed_dir: /ifs/data/molecpathlab/quicksilver/to_be_demultiplexed/processed
script: /ifs/data/molecpathlab/scripts/demultiplexing/demultiplex-NGS580-WES.sh
logdir: /ifs/data/molecpathlab/quicksilver/automatic_demultiplexing_logs
email_recipients: '#MolecularPathology@nyumc.org'
reply_to_servername: 'nyumc.org'
seqtype: NGS580
